version: '3'
services:
  plex:
    image: linuxserver/plex
    volumes:
      - ${CONF_DIR}/plex:/config
      - ${DATA_DIR}/tv:/data/tvshows
      - ${DATA_DIR}/movies:/data/movies
      - ${TMP_DIR}/transcode:/transcode
    env_file:
      - ./env_files/common.env
    environment:
      - PGID
      - PUID
      - VERSION=latest
    ports:
      - 32400:32400
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    restart: always
  sickrage:
    image: linuxserver/sickrage
    volumes:
      - ${CONF_DIR}/sickrage:/config
      - ${DATA_DIR}/tv:/data/tvshows
      - ${DATA_DIR}/downloads:/downloads
    env_file:
      - ./env_files/common.env
    environment:
      - PGID
      - PUID
    ports:
      - 8081:8081
    restart: always
  transmission:
    image: haugene/transmission-openvpn
    env_file:
      - ./env_files/common.env
    environment:
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - OPENVPN_PROVIDER
      - OPENVPN_CONFIG=Switzerland
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/tmp
      - TRANSMISSION_INCOMPLETE_DIR=/tmp/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
    extra_hosts:
      - 0.0.0.0:localhost
    volumes:
      - ${CONF_DIR}/transmission:/config
      - ${TMP_DIR}/transmission:/tmp
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 9092:9091
    restart: always
    privileged: true
  transmission-proxy:
    image: haugene/transmission-openvpn-proxy
    links:
      - transmission
    ports:
      - 8080:8080
  couchpotato:
    image: linuxserver/couchpotato
    volumes:
      - ${CONF_DIR}/couchpotato:/config
      - ${DATA_DIR}/movies:/movies
      - ${DATA_DIR}/downloads:/downloads
    env_file:
      - ./env_files/common.env
    environment:
      - PGID
      - PUID
    ports:
      - 5050:5050
    restart: always
