version: '3'
services:
  plex:
    image: linuxserver/plex
    volumes:
      - ${CONF_DIR}/plex:/config
      - ${DATA_DIR}/tv:/data/tvshows
      - ${DATA_DIR}/movies:/data/movies
      - ${TMP_DIR}/transcode:/transcode
    env_file:
      - ./env_files/common.env
    environment:
      - PGID
      - PUID
      - VERSION=latest
    ports:
      - 32400:32400
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    restart: always
  sickrage:
    image: linuxserver/sickrage
    volumes:
      - ${CONF_DIR}/sickrage:/config
      - ${DATA_DIR}/tv:/data/tvshows
      - ${DATA_DIR}/downloads:/downloads
    env_file:
      - ./env_files/common.env
    environment:
      - PGID
      - PUID
    ports:
      - 8081:8081
    restart: always
